---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates (CentOS)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: install updates (Ubuntu, Debian)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution in [ "Debian", "Ubuntu"]

- hosts: all
  become: true
  tasks:
    - name: add ssh key for simone
      tags: always
      ansible.posix.authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIACBSmFgMek1WjJif8W2Iz4W9YoVMu9wCfiTja+GJq3h ansible"
        state: present

- hosts: workstations
  become: true
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /usr/local/bin
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: install unzip
      package:
        name: unzip
        state: latest

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  tags: apache,apache2,ubuntu
  become: true

  tasks:
    - name: install firewalld (Centos)
      tags: apache,centos,httpd
      dnf:
        name:
          - firewalld
        state: latest
      when: ansible_distribution == "CentOS"

    - name: start firewalld (CentOS)
      tags: apache,centos,httpd
      service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: allow 443 firewall (CentOS)
      tags: apache,centos,httpd
      ansible.posix.firewalld:
        port: 443/tcp
        permanent: yes
        immediate: yes
        state: enabled
      when: ansible_distribution == "CentOS"

    - name: allow http firewall (CentOS)
      tags: apache,centos,httpd
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: yes
        immediate: yes
        state: enabled
      when: ansible_distribution == "CentOS"

    - name: install httpd package with php (Centos)
      tags: apache,centos,httpd
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: configure httpd service (CentOS)
      tags: apache,centos,httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: install apache2 with php (Ubuntu)
      tags: apache,ubuntu,httpd
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in [ "Debian", "Ubuntu"]

    - name: change admin email address
      tags: apache,centos,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^ServerAdmin"
        line: ServerAdmin somebody@somewhere.net
      when: ansible_distribution == "CentOS"
      register: httpd

    - name: restart httpd (CentOS)
      tags: apache,centos,httpd
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        #  directory 'files' is assumed
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true

  tasks:
    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      tags: ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution in [ "Debian", "Ubuntu"]

- hosts: file_servers
  become: true

  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
